GET http://localhost:3002/api/persons
###
GET http://localhost:3002/api/persons/648
 
###
DELETE  http://localhost:3002/api/persons/648
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"wswssw",
    "number": "555"
    
}

### 
GET https://fsphonebook-e004.onrender.com/api/persons

###
GET https://fsphonebook-e004.onrender.com/api/persons/1


###
POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name":"llttl",
    "number": "55S5"
    
}